version: '3'

services:

  vuespa-site:
    build:
      context: .
      dockerfile: src/frontend/vuespa/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - aspnetcore.api
    
  aspnetcore.api:
    build:
      context: .
      dockerfile: src/backend/MyApi/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"